### PR TITLE
Build: Remove multiversion, switch over to fabric loom

### PR DESCRIPTION
**Pull request by camnwalter**
I will do some more testing to make sure everything works. Opening just to keep this on the radar.

Also I made it so it doesn't bundle fabric language kotlin or fabric api, but can revert that if it makes more sense to keep them.

### CODE REVIEW

**Review by mattco98 — APPROVED** [review]
lgtm, not sure about the API bundling. What do other mods do? Might be a good idea to avoid a loader update breaking the mod like it did with 15.3. 

Also I would recommend setting your Java continuation indent setting to 4 and max line length to 120 to match my settings (can we commit that to the .idea folder somehow?). I'll probably do a project-wide format at some point so dw about it in this PR.

**Comment by camnwalter** [comment]
> lgtm, not sure about the API bundling. What do other mods do? Might be a good idea to avoid a loader update breaking the mod like it did with 15.3.
> 
> Also I would recommend setting your Java continuation indent setting to 4 and max line length to 120 to match my settings (can we commit that to the .idea folder somehow?). I'll probably do a project-wide format at some point so dw about it in this PR.

Added the .idea/codeStyles folder.  Are there any other settings you see that should also be added?

**Comment by mattco98** [comment]
> Added the .idea/codeStyles folder. Are there any other settings you see that should also be added?

Nah that's fine

> As for including/excluding fabric api, the fabric example mod doesn't include it so a lot of mods will keep it as just modImplementation. Also not really sure what caused the loader update to break ct so I can't guarantee this will be any different. Perhaps moving from essential's loom would make the compatibility better?

No clue, but if the loader is small (which I assume it is), then I don't really see any reason not to include it.

**Comment by camnwalter** [comment]
> No clue, but if the loader is small (which I assume it is), then I don't really see any reason not to include it.

Looking around fabric discord, I'm not entirely sure on the specifics but that seems like a bad idea.

**Review by DJtheRedstoner — CHANGES_REQUESTED** [review]
The 2 actions workflows should be updated to include `gradle/*.versions.toml` in the cache key hash for proper cache invalidation.

**Pull request merged**
